forge 'http://forge.puppetlabs.com'

mod 'cas',
  :git => 'https://github.com/huit/puppet-cas.git'
  :ref => 'iam'

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/java'
mod 'puppetlabs/vcsrepo'
mod 'maestrodev/maven'
mod 'maestrodev/wget', '>= 1.0.0'
